apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::397758300362:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-87EY7469JKRN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::397758300362:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-31T11:24:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1684"
  uid: b2f0cbad-78d0-4967-a319-2f9d7da32582
